### ISSUE TITLE
[Suggestion]: Stylized Text in Anvils/Whilst Using Name Tags

### ISSUE THREAD

**Issue by Illios42** [Fuzss/easyanvils#1]
### Suggestion (Required)

Already love this mod, since I have been looking for a way to get rid of the "too expensive" for ages now.

Anyways, I think it could be a great visual enhancement if one were able to use Minecraft's § codes (both for color and for things like writing in italic) in an anvil/ in the new name tag gui to further customize item appearance or give entities colored names! It's not something any maintained mods offer as far as I am aware, so it would be a unique addition to this one

**Comment by Fuzss** [comment]
Wow, that's an awesome suggestion. Thank you so much!
Added in v4.0.1.
