### ISSUE TITLE
[Bug]: Can't open Anvils on latest update. (v4.0.5)

### ISSUE THREAD

**Issue by Gbergz** [Fuzss/easyanvils#11]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.5

### Notes (Required)

Place anvil.
Can't open the GUI. Nothing happens.

### latest.log (Optional)

None.

**Comment by Fuzss** [comment]
Do you have Apotheosis installed?

**Comment by Gbergz** [comment]
Yes I do, actually.

**Comment by Fuzss** [comment]
Apotheosis uses registry replacement instead of Mixins to apply its anvil changes. This is not compatible with Easy Anvils right now, I'll look into it.

**Comment by Gbergz** [comment]
Ah gotcha.

**Comment by Fuzss** [comment]
Fixed in v4.0.6 with dedicated compat for Apotheosis quite a while back already, thanks for reporting!
