### ISSUE TITLE
[Suggestion]: Change the Prefix from § to & similarly to the "Server Utilities" mod

### ISSUE THREAD

**Issue by LordCodFish** [Fuzss/easyanvils#12]
### Suggestion (Required)

When renaming an item in the anvil and flexing it using the Quark feature, I get kicked from my server due to illegal characters in chat. Seeing as it's possible in another mod, Server Utilities, I'm wondering if it might be possible here, to use the & symbol instead of §. Here is my log
[latest.log](https://github.com/Fuzss/easyanvils/files/10041749/latest.log)

**Comment by Fuzss** [comment]
I don't think using an alternative prefix such as `&` is necessary, it should be enough to simply convert the item name to Minecraft's current component text system in favor of using the legacy `§` prefix based text system. 

I'll try it at some point.

**Comment by Fuzss** [comment]
Thanks for reporting! Fixed in v4.0.9.
