### ISSUE TITLE
[Bug]: Incompatability with Impaled mod's Loyalty 4 & Riptide

### ISSUE THREAD

**Issue by ANormalRaft** [Fuzss/easyanvils#15]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.6

### Notes (Required)

Current Behavior: A loyalty 4 trident (trident with loyalty 3 combined with a Heart of the Sea at a Smithing Table) cannot receive riptide 3 as it should as seen in the Impaled video (at 11:26):
https://www.youtube.com/watch?v=9JhblcRTRu8

Steps to Reproduce:
1. Enchant a trident with Loyalty 3
2. In a Smithing Table, combine said trident with a Heart of the Sea to get a Loyalty 4 trident bound to you
3. (Make sure you are in survival!) In an anvil, attempt to combine said trident with a Riptide 3 enchantment book.

Expected Behavior: The enchantment should go through, getting a Loyalty 4 & Riptide 3 trident

**Comment by Fuzss** [comment]
Thanks for the report! Should be fixed in v4.0.7. Please reopen if it's not.
