### ISSUE TITLE
[Bug]: unbreaking 3 + 3 = 3

### ISSUE THREAD

**Issue by GreenForzeGaming** [Fuzss/easyanvils#17]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

latest

### Notes (Required)

cant combine level 3 unbreaking too get 4

**Comment by Fuzss** [comment]
That’s not a feature. Easy Anvils only makes it so when you already have an item with an enchantment above the max level it will stay at that level when working the item in an anvil. Vanilla will reduce higher levels to the max level in the anvil, Easy Anvils only fixes that.

**Comment by GreenForzeGaming** [comment]
well then this mod breaks that aspect from apothiosis, cous without your mod now i suddenly can do 3 + 3 = 4
