### ISSUE TITLE
[Bug]: this mod is responsable for 3+3=3

### ISSUE THREAD

**Issue by GreenForzeGaming** [Fuzss/easyanvils#18]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

latest

### Notes (Required)

well then this mod breaks that aspect from apothiosis, couse without your mod now i suddenly can do 3 + 3 = 4

ive set all my enchants to be level 4 max in apotheosis, with this mod it stops working.

**Comment by Fuzss** [comment]
That makes more sense, thanks.

**Comment by GreenForzeGaming** [comment]
thx for dealing with us players XD, i bet its a heck of a task too fix all these things. was looking forward to make my items have colored text and stuff but ill have too wait XD, usually how long does things like this take?

**Comment by GreenForzeGaming** [comment]
is this going too be fixed soon... my mod pack ive wanted to play is brocken couse of this...

**Comment by Fuzss** [comment]
Just remove Easy Anvils for now.

**Comment by GreenForzeGaming** [comment]
i would if the mod wasn't so good. lol

**Comment by Fuzss** [comment]
Haha thanks.

Well there is a way how you can fix this yourself for now:
1. Open the Apotheosis jar and go to `coremods/ench/ench_info_redirector.js`
2. Find this line in the file: https://github.com/Shadows-of-Fire/Apotheosis/blob/6eb65760a88edff1fbe030ba6137725fe85bb65b/src/main/resources/coremods/ench/ench_info_redirector.js#L61
3. Add `fuzs.easyanvils.world.inventory.ModAnvilMenu`
4. Save the file and the jar

You need to do this again when updating Apotheosis at some point.

**Comment by GreenForzeGaming** [comment]
interesting. thx!

**Comment by Fuzss** [comment]
Thanks for the report! Should be fixed in v4.0.7. Please reopen if it's not.

**Comment by GreenForzeGaming** [comment]
LOVELY! thx yourself! without this mod there would not have been anything here XD, im glad i could help! thx again!
