### ISSUE TITLE
Crashing on start

### ISSUE THREAD

**Issue by ForeheafBoiii** [Fuzss/easyanvils#19]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.6

### Notes (Required)

1. Press play in launcher
2. Game crashes before loading

### Crash Report (Required)

Doesn't give me a crash report, probably because the game doesn't launch

**Comment by Fuzss** [comment]
Did you install Puzzles Lib?

I also need the latest.log file.

**Comment by ForeheafBoiii** [comment]
Oop- I was just dumb. I downloaded the fabric version of Puzzles lib. It's working now
