### ISSUE TITLE
[Crash]: Typing emoji in the name of the item on anvil causes crash.

### ISSUE THREAD

**Issue by MrTonyNeon** [Fuzss/easyanvils#20]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v.4.0.6

### Notes (Required)

1. open anvil gui
2. add some item
3. try to add any unicode emoji that minecraft support
4. game crashes

### Crash Report (Required)

https://gist.github.com/MrTonyNeon/018046f8ff4cacb564f906a7b5d48c2b

**Comment by Fuzss** [comment]
Thanks for reporting! Fixed in v4.0.9.
