### ISSUE TITLE
[Suggestion]: Compatibility with Fabrication & Forgery's 'Swap Conflicting Enchants'

### ISSUE THREAD

**Issue by JLUsr** [Fuzss/easyanvils#21]
### Suggestion (Required)

Though the feature [Swap Conflicting Enchants](https://falsehoodmc.github.io/#mechanics.extra.swap_conflicting_enchants) from Fabrication & Forgery is working with EasyAnvils, the anvil will not actually allow for the conflicting enchant to be applied when EasyAnvils is installed, effectively disabling the feature. Compatibility for this would be nice if at all possible. I only tested this with Fabric 1.19.2, v3.2.0 of Fabrication, and V4.0.6 of EasyAnvils.

**Comment by Fuzss** [comment]
Thanks for the report! Should be fixed in v4.0.7. Please reopen if it's not.
