### ISSUE TITLE
[Bug]: Right clicking on an anvil crashes the game

### ISSUE THREAD

**Issue by thelegitdolt** [Fuzss/easyanvils#22]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.8

### Notes (Required)

Right clicking an anvil crashes the game

### latest.log (Optional)

https://gist.github.com/thelegitdolt/bd035319df91e9b6271e92a194853bb0

**Comment by thelegitdolt** [comment]
https://gist.github.com/thelegitdolt/d943bc98deea233029a959011c6d99e7 < crash report

**Comment by thelegitdolt** [comment]
can still reproduce in v4.0.8

**Comment by ingrac42** [comment]
[crash-2023-03-08_21.52.32-server.txt](https://github.com/Fuzss/easyanvils/files/10925682/crash-2023-03-08_21.52.32-server.txt)
[crash-2023-03-08_22.00.54-server.txt](https://github.com/Fuzss/easyanvils/files/10925683/crash-2023-03-08_22.00.54-server.txt)

[crash-2023-03-08_15.14.22-client.txt](https://github.com/Fuzss/easyanvils/files/10925717/crash-2023-03-08_15.14.22-client.txt)


Updated to 4.0.8 today and server crashes when using an Anvil.

**Comment by Fuzss** [comment]
Thanks for reporting! Fixed in v4.0.9 for real this time, missed something with the last fix.
