### ISSUE TITLE
[Crash]: when trying to open settings menu

### ISSUE THREAD

**Issue by FearAK** [Fuzss/easyanvils#27]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

EasyAnvils-v4.0.11-1.19.2-Forge.jar

### Notes (Required)

I'm trying to make my own private pack and I'm using almost all your mods, but for some reason when I open the game and try to go into settings to change video settings I crash and get this log which has some other mods in it aswell that seem to might be the cause but I noticed the easy anvil aswell so I figured I'd ask you if you can see what the issue is?

### Crash Report (Required)

https://gist.github.com/FearAK/3fda9ee5094ef5e3ec7f107ee645b737

**Comment by Fuzss** [comment]
You need to send the actual crash-report. ˋ
