### ISSUE TITLE
[Bug]: Create's Display Board cannot be interacted with name tags

### ISSUE THREAD

**Issue by mageowl** [Fuzss/easyanvils#28]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.11

### Notes (Required)

Current behavior: Right-clicking a display board from the _Create_ mod does nothing.
Expected behavior: It is supposed to set the text on the display board to the text in the name tag.

It works as expected without easyanvils installed.

**Comment by Fuzss** [comment]
Are you crouching while right-clicking? That should be overridden by Easy Anvils.
But if you're not crouching Easy Anvils shouldn't interfere with that.
Also have you used formatting codes on your name tag?

**Comment by Fuzss** [comment]
Also try if disabling the `edit_name_tags_no_anvil` option allows the Create renaming to work.

**Comment by mageowl** [comment]
This is my fault. Create's clipboard replaced this functionality of the name tag.
