### ISSUE TITLE
[Bug]: Cant launch

### ISSUE THREAD

**Issue by RevMirin** [Fuzss/easyanvils#32]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.11

### Notes (Required)

launch server lol

### latest.log (Optional)

[latest.log](https://github.com/Fuzss/easyanvils/files/12115421/latest.log)

**Comment by Fuzss** [comment]
Make sure to install the latest version of Forge Config Api Port: https://legacy.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric/files/4401535
