### ISSUE TITLE
[Suggestion]: Allow the usage of custom RGB colors on item names

### ISSUE THREAD

**Issue by KuryKat** [Fuzss/easyanvils#41]
### Suggestion (Required)

I am not sure if it's possible, however, it would be *really* cool if we could choose custom colors for our items, some plugins for latest Minecraft servers already allow us to do so, and there is even some cool websites like [this one](https://www.birdflop.com/resources/rgb/) that allow us to create a Gradient Color for renaming items!

So I would like to suggest that being included, if possible, in the mod, cause that'd bring a really cool feature!

The format could be something like "§x§R§R§G§G§B§B", where §R§R is the Red, §G§G is the Green, and §B§B is the Blue, like some plugins use, the website I quoted show the most common formats.

An example usage would be §x§8§b§0§0§0§0 that would output a Dark Red!

Note: as far as I know Minecraft started allowing the usage of custom colors in commands, for example, after 1.16, where you can use the "color" property with an RGB HEX (#RRGGBB) code

**Comment by Fuzss** [comment]
Thanks for the suggestion! While this would be cool to have it‘s unfortunately way too much effort to implement, and I also believe the default colors provided via formatting codes already provide enough variety for customising equipment. 

Also I don‘t really see how this feature could be implemented in an intuitive way that would make it accessible to a lot of players.

**Comment by KuryKat** [comment]
Fair enough, thanks for the feedback!
