### ISSUE TITLE
[Suggestion]: Opt-in for modded anvils

### ISSUE THREAD

**Issue by Noaaan** [Fuzss/easyanvils#43]
### Suggestion (Required)

A while ago I was recommended to look into adding compatibility for my modded anvils in Mythic Metals, although from testing out things I realized that Easy Anvils currently does not allow for this. The Mixin is currently hardcoded to ignore anything but vanilla anvils.
It would be nice if there was some tag or something similar which would allow me to add a configurable option for Easy Anvil support.

**Comment by Fuzss** [comment]
Yeah, I added this intentionally as a lot of modded anvils I found tend to change anvil mechanics (like increasing the repair limit) and my implementation being designed around the vanilla anvil would usually override those modified mechanics.

My plan is to overhaul the mod a little though by replacing the vanilla anvil block in an effort to avoid using mixins. With that concept it would definitely be much easier to offer a proper api for other mods that wish to utilize the new mechanics offered by Easy Anvils while keeping their own.

**Comment by kurtramone** [comment]
I have your mod but Apotheosis changes vanilla anvils in some, I believe to be able to enchant them, your mod is not compatible, would be nice a compatibility

**Comment by Fuzss** [comment]
As of v20.4.0 for Minecraft 1.20.4 modded anvils are supported by default. Would be great if you could give some feedback once you update Mythic Metals if everything works as expected.

If something doesn't work as expected there is also the `easyanvils:unaltered_anvils` block tag for opting out.

**Comment by Noaaan** [comment]
Seems to work fine for me, good stuff

![image](https://github.com/Fuzss/easyanvils/assets/4163353/9d9bd39d-c70c-4285-8fc1-b18d6f69c121)

![2024-03-17_01 54 43](https://github.com/Fuzss/easyanvils/assets/4163353/7e0fc870-383f-4cd0-9d0c-9c4474e9f164)
