### ISSUE TITLE
[Crash]: Unhandled game exception on launch

### ISSUE THREAD

**Issue by BioMasterZap** [Fuzss/easyanvils#49]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

v20.4.2

### Other Mods Involved (Required)

No

### Notes (Required)

I am unsure what exactly is causing the issue, but when I added Easy Anvil to test it for my mod pack, the game would only launch briefly before immediately closing. I also had the same thing happen when I tested VisualWorkbench.

Because of how it crashed it didn't generate a crash log, so I included the full log instead. I think the relevant part is Line 690 and down with "Cached all modded block culling states" and then the crash for "Unhandled game exception".

I did test it with just Easy Anvil, Puzzles Lib, Forge Config API Port, and Fabric API on a different profile without any issues. But I also have been running all the mods in the pack, including Puzzles Lib and Forge Config API Port for Nether Chested, for days now without encountering this issue unless I added Easy Anvil or VisualWorkbench (the log looked the same for VisualWorkbench, only with line 720 listing VisualWorkbench instead of Easy Anvil).

Also, EasyMagic didn't have any issues, just Easy Anvil and VisualWorkbench, so probably some conflict with them and fastutil, modernfix, and/or continuity. Let me now if there is anything else I can provide or if it should be reported to one of the other mods.

### Crash Report (Required)

https://gist.github.com/BioMasterZap/36b3913e4f1ec5803d391166d77ad6f1

**Comment by Fuzss** [comment]
Try without Continuity.

**Comment by BioMasterZap** [comment]
I did some further testing and managed to resolve it. Removing Continuity or ModernFix will make the game load up without any issue, but when I tested just Easy Anvil with Continuity and/or ModernFix in a separate profile, it also worked fine. After being confused for a good half an hour or so, I realized that it was because the test profile had fresh configs while my Mod Pack was built off of Fabulously Optimized, which had "mixin.perf.dynamic_resources=true" in the ModernFix config.

It seems was the combination of Easy Anvil/Visual Workbench, Continuity, and ModernFix with dynamic resources enabled. After changing mixin.perf.dynamic_resources back to false (the default), it is working fine. So, if anyone else wants to use Easy Anvil or Visual Workbench in Fabulously Optimized or a pack based off of it, that seems to be the fix.

**Comment by Fuzss** [comment]
So removing Continuitiy, but keeping `mixin.perf.dynamic_resources=true` does work?

**Comment by BioMasterZap** [comment]
Well, I went to double-check before replying and it turns out it isn't just Continuity, Easy Anvil, and ModernFix with "mixin.perf.dynamic_resources=true", but Continuity, Easy Anvil, ModernFix, and MoreCulling with "mixin.perf.dynamic_resources=true". With "mixin.perf.dynamic_resources=true", removing any one of Continuity, Easy Anvil, ModernFix, or MoreCulling will allow the game to launch and work normally. With all four mods present, it will crash unless ModernFix's "mixin.perf.dynamic_resources" is false (its default config option).

So yes, you can remove Continuity with mixin.perf.dynamic_resources=true, but you can also remove MoreCulling with mixin.perf.dynamic_resources=true. A combination of any three (Continuity, Easy Anvil, ModernFix, and MoreCulling) with ModernFix's mixin.perf.dynamic_resources=true seems to be fine, but all four is when the issue occurs. Not sure if there is anything that can or should be done on your or the other mod's ends since it seems like a pretty specific circumstance, but Continuity, ModernFix with mixin.perf.dynamic_resources=true, and MoreCulling are all default mods/config options for Fabulously Optimized.

If you did want to look into it further, here is the log with just Easy Anvil (and Puzzles Lib and Forge Config API Port), Continuity, ModernFix (with mixin.perf.dynamic_resources=true), MoreCulling (and Cloth Config), and Fabric API present. It looks to be the same as before just with fewer mods and a shutdown failure at the end.
https://gist.github.com/BioMasterZap/f6704a69de0d0514fb886aaa1c503fec
