### ISSUE TITLE
[Suggestion]: Here is a Mexican Spanish Translation

### ISSUE THREAD

**Issue by TheLegendofSaram** [Fuzss/easyanvils#55]
### Mod Loader (Optional)

Fabric

### Minecraft Version(s) (Optional)

1.20.1

### Mod Version(s) (Optional)

8.0.2

### Suggestion (Required)

I already did it, I dont want to do a pull request cause, you know... the translation is super small
[es_mx.json](https://github.com/Fuzss/easyanvils/files/14738972/es_mx.json)

**Comment by Fuzss** [comment]
#58
