### ISSUE TITLE
[Bug]: Dup Items

### ISSUE THREAD

**Issue by EastMc** [Fuzss/easyanvils#59]
### Mod Loader (Required)

⸺

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

20.4.3

### Other Mods Involved (Required)

Yes

### Notes (Required)

Its possible to dup items in multiplayer servers.
it is only necessary for someone to place the item and rename it, and at the same time, the person who renamed it takes the item, and someone outside takes the item that is on the anvil, thus, both of them will have taken the item, duplicating it.

### latest.log (Required)

https://paste.gemwire.uk/view/f134a263

**Comment by EastMc** [comment]
Sorry forgot to say that the mod loader is Fabric.

**Comment by Fuzss** [comment]
Fixed in v20.4.6, thanks!
