### ISSUE TITLE
[Suggestion]: Can you make it compatible with Better End and Better Nether mods ;)?

### ISSUE THREAD

**Issue by LocChsNgu** [Fuzss/easyanvils#60]
### Mod Loader (Optional)

Fabric

### Minecraft Version(s) (Optional)

1.20.1

### Suggestion (Required)

Some of the anvils from Better End and Better Nether Mods don't work with Easy Anvils mod :((

**Comment by Fuzss** [comment]
Mod support was added in the 1.20.4 version, but those mods unfortunately have an anvil implementation too different from vanilla so the won't be supported.
