### ISSUE TITLE
Just My Thanks !

### ISSUE THREAD

**Issue by AmibeSkyfy16** [Fuzss/easyanvils#62]
### Mod Loader (Optional)

Fabric

### Minecraft Version(s) (Optional)

1.20.4

### Mod Version(s) (Optional)

v20.4.3

### Suggestion (Required)

My sincere thanks and appreciation for the enormous work of creating and keeping the mods up to date !
I own a small private server, and people are very grateful to be able to play recent versions of Minecraft with your mods.

**Comment by Fuzss** [comment]
Thanks a lot for the kind words! We also have a Discord server btw if you want to come hang out or have problems / questions. :)

https://lunapixel.studio/discord
