### ISSUE TITLE
[Bug]: Incompatibility with itemborders when renaming

### ISSUE THREAD

**Issue by Arclightning7** [Fuzss/easyanvils#63]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

8.0.2

### Other Mods Involved (Required)

Yes

### Notes (Required)

![image](https://github.com/Fuzss/easyanvils/assets/111223268/bf5aab6b-a3e1-4509-b796-9bffcb6af1be)
For some reason item borders refuses to apply an item border to a renamed enchanted weapon when renaming with an anvil with this mod.

### latest.log (Required)

https://paste.gemwire.uk/view/c8b78ba1

**Comment by Fuzss** [comment]
Append `§b` before the item name, like `§bDiamond Pickaxes`.

Item Borders gets the border color from the item name color, which is aqua by default for enchanted items in vanilla. Easy Anvils allows you to set the color yourself independently of the item being enchanted or not, hence it defaults to white.
