### ISSUE TITLE
Game Crashes with the mod.

### ISSUE THREAD

**Issue by Crafty1340** [Fuzss/easyanvils#64]
### Mod Loader (Required)
Forge
⸺

### Minecraft Version(s) (Required)

1.19.2

### Mod Version(s) (Required)

v4.0.11

### Other Mods Involved (Required)

⸺

### Notes (Required)

I have no clue... Forge 43.3.7

### Crash Report (Required)

None.

### latest.log (Optional)

None. Exit Code 1

**Comment by Fuzss** [comment]
Invalid without crash report and log. At least the log always generates.
