### ISSUE TITLE
[Crash]: When breaking anvil with items still inside

### ISSUE THREAD

**Issue by Proxi2** [Fuzss/easyanvils#66]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

v21.0.0

### Other Mods Involved (Required)

No

### Notes (Required)

1. Place down anvil
2. Put item into anvil
3. Break anvil with item still inside

### Crash Report (Required)

https://pastebin.com/Qf3uTZMp

### latest.log (Optional)

https://mclo.gs/0fH1MHm

**Comment by Proxi2** [comment]
can confirm with new update the break crash is fixed. thank you!

**Comment by Fuzss** [comment]
Thanks for reporting!
