### ISSUE TITLE
[Crash]: Breaking an Anvil

### ISSUE THREAD

**Issue by Wash113** [Fuzss/easyanvils#67]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

v21.0.0

### Other Mods Involved (Required)

Yes

### Notes (Required)

Hey there! Got a server crash for you. I interacted with a pre placed anvil and got the popup saying I needed to break and replace the anvil. Did that, started working fine but the anvil placed rotated 90 degrees from where it should. I tried to break it with my pick, but it was unbreakable. I switched to creative to break it, and it crashed the server. Happy hunting!

### Crash Report (Required)

https://mclo.gs/ha24BCs

### latest.log (Optional)

https://mclo.gs/OTT5Hup

**Comment by Wash113** [comment]
Also for the record, while it doesnt seem to crash, Easy Magic also has the weird breaking issue. But it doesn't crash the server when broken in creative.

**Comment by Fuzss** [comment]
The breaking crash is fixed now in v21.0.1. For the weird rotation, that's a visual glitch with the model which will be addressed in the next version.

**Comment by Wash113** [comment]
Copy that, thanks as always @Fuzss !

**Comment by Fuzss** [comment]
The model rotation bug is now fixed in v21.0.2. Thanks for reporting!

**Comment by Wash113** [comment]
No problem @Fuzss , I appreciate how quick to fix you are!!
