### ISSUE TITLE
[Bug]: Anvil texture locked to the North/South axis

### ISSUE THREAD

**Issue by ffuentesm** [Fuzss/easyanvils#69]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

21.0.2

### Other Mods Involved (Required)

No

### Notes (Required)

![image](https://github.com/Fuzss/easyanvils/assets/44974827/242df00d-8d78-46f1-9c9c-8e10e538159d)
As you can see, the texture and the block hitbox are not aligned 

### latest.log (Required)

[latest.log](https://github.com/user-attachments/files/16120284/latest.log)

**Comment by Fuzss** [comment]
Can you reproduce the issue with just Easy Anvils (+dependencies) installed (especially without ModernFix)?

**Comment by ffuentesm** [comment]
YEs Same error 
![image](https://github.com/Fuzss/easyanvils/assets/44974827/7bb828b1-38a4-471e-8228-edd742bd6337)

**Comment by Fuzss** [comment]
Your log still shows a bunch of other mods installed. Please test Easy Anvils just on it's own.

**Comment by ffuentesm** [comment]
> Your log still shows a bunch of other mods installed including ModernFix. Please test Easy Anvils just on it's own.

Strange, because I literally ran a world with just those two mods. 
![image](https://github.com/Fuzss/easyanvils/assets/44974827/0df17c8c-b0d9-46b4-89e6-25f0dc7ad8d0)
![image](https://github.com/Fuzss/easyanvils/assets/44974827/30f58a03-ca6b-444c-a980-c8553909f0f5)

Log: [latest.log](https://github.com/user-attachments/files/16120418/latest.log)

**Comment by Fuzss** [comment]
Yeah, that log shows the minimal setup, thanks! No clue though what's causing this...

**Comment by Fuzss** [comment]
Fixed by updating Puzzles Lib to v21.0.20.
