### ISSUE TITLE
[Bug]: Incompatibility with Ledger mod

### ISSUE THREAD

**Issue by Fuzss** [Fuzss/easyanvils#7]
We are facing a near identical issue, though our configuration is different.
* We are running the Fabric Better MC modpack 1.19.2.
* Atop of those mods, we also run Ledger (grief protection) and dynmap-fabric.
* The issue ONLY takes place on our server, it does not occur in singleplayer.
* In v7.5 of the Modpack, the issue first started - the the errors in the logs were different from now.
* In v8 of the Modpack, the logs were spammed with a bunch of Exceptions referencing something from the Ledger mod.

Thus, I believe Ledger and EasyAnvils have some sort of incompatibility. I created a Minecraft server running Ledger and EasyAnvils and successfully reproduced the bug.
v4.0.3 did not fix it, though it seems as though the mod is currently being updated to v4.0.4?
I can share various logs in a sec

_Originally posted by @Hellession in https://github.com/Fuzss/easyanvils/issues/4#issuecomment-1282530845_

**Comment by Fuzss** [comment]
@Hellession Moving this to a separate issue as I'm pretty sure this is not related to the other report.

Ledger does something with the anvil here, maybe it is related: https://github.com/QuiltServerTools/Ledger/blob/master/src/main/java/com/github/quiltservertools/ledger/mixin/AnvilScreenHandlerMixin.java

**Comment by Fuzss** [comment]
Would also be great if you could include any of the logs you've mentioned.
https://gist.github.com/Fuzss/866b384d353912986e37b17eeef7a285

**Comment by Hellession** [comment]
Tried with v4.0.4 - the issue is still there.

Here is the server log file of the test instance I created running only EasyAnvils, Ledger and their dependencies:
https://gist.github.com/Hellession/0868ba133e09cc0a64eae2a5280595af

**Comment by Fuzss** [comment]
But Easy Anvils with Ledger works fine for you?

**Comment by Hellession** [comment]
Items disappear when you take them out of the anvil, like the other bug report showed in their video clip, it's almost identical in how it behaves. We lost lots of our items through the anvil this way.
One thing is that SHIFT clicking appeared to be safe.

So yeah it doesn't really work very well for us.
I can try and record footage of this happening, but again, it's identical to how it happens in the video clip shared by purejosh in Issue #4

**Comment by Fuzss** [comment]
Sorry, that was supposed to say 'without'. So have been able to try if just Easy Anvils works without issues? Maybe it's just something I missed and Ledger doesn't have a conflict at all...

**Comment by Hellession** [comment]
I removed Ledger and Fabric Kotlin from the test server and EasyAnvils on its own worked without any issue.
I also tried *only* including Fabric Kotlin (but no Ledger) and EasyAnvils also worked without any issue.

It appears to only cause problems with Ledger

**Comment by Hellession** [comment]
The bug appears to be gone. Just tried with Ledger installed and saw no issue with disappearing items

**Comment by Fuzss** [comment]
Sounds great, I’ll publish the fix later on Curse/Modrinth.

**Comment by Hellession** [comment]
Thank you!

**Comment by purejosh** [comment]
I also use ledger, for what it's worth.

**Comment by Fuzss** [comment]
Ah, so it was the same issue after all, interesting. Although I really thought the issue you were having came from something I fixed in v4.0.3, oh well.

So v4.0.5 is out now with the fix for Ledger.

**Comment by Fuzss** [comment]
@Hellession As there‘ve been new reports of items disappearing, have you had another incident or is everything working fine?

**Comment by purejosh** [comment]
What exactly are we suspicious of the problem being? I'd be happy to test. 

To my knowledge, I've noticed items disappearing very randomly when closing the anvil GUI. I'm not sure I could faithfully reproduce it, but I'm happy to help if I can.

Just tossing ideas out there, would it be incredibly difficult to add a toggle inventory for the anvil option in the config? Essentially keeping all of the features except for the persistent inventory. My initial assumption is yeah, that wouldn't be easy...

**Comment by Hellession** [comment]
> @Hellession As there‘ve been new reports of items disappearing, have you had another incident or is everything working fine?

Everything works fine and well ever since the 4.0.5 update came out, running Fabric Better MC v9 with Ledger and dynmap. No issues here, at least from my personal experience.
