### ISSUE TITLE
[Crash]: Neoforge 21.0.82 changes crash on launch

### ISSUE THREAD

**Issue by ffuentesm** [Fuzss/easyanvils#70]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

21.0.2

### Other Mods Involved (Required)

No

### Notes (Required)

![image](https://github.com/user-attachments/assets/2cde2a3a-518b-48de-9745-556fac442efb)

### Crash Report (Required)

https://pastebin.com/pK5Frguu

**Comment by Fuzss** [comment]
Thanks, fixed in Puzzles Lib v21.0.13.
