### ISSUE TITLE
[Crash]: When Opening Any Save File

### ISSUE THREAD

**Issue by VladAndreiMorariu** [Fuzss/easyanvils#73]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

21.0.2

### Other Mods Involved (Required)

No

### Notes (Required)

Every time I try to open any world or even when I create a new one, the game crashes

### Crash Report (Required)

https://gist.github.com/VladAndreiMorariu/a38cd5f9ce4652bed246d78f153b716c

**Comment by Fuzss** [comment]
Delete the Easy Anvils config in .minecraft/config.

**Comment by Fuzss** [comment]
Fixed via PuzzlesLib v21.0.19, deleting the config is no longer necessary.
