### ISSUE TITLE
[Bug]: No Minecraft world can load or be created with the mod in the folder

### ISSUE THREAD

**Issue by newperson-byte** [Fuzss/easyanvils#74]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

v21.0.2

### Other Mods Involved (Required)

Yes

### Notes (Required)

So whenever I put the mod in a mod folder and try to start up a world it can never load and always crashes. I always thought it was because of the other mods I had and for some reason without the anvil mod Minecraft runs perfectly. So I removed them but nothing was fixed, The only mods that are in the folder are Fabric API, ForgeConfigAPIPort and PuzzlesLib but even still Minecraft can't even start with this mod which is such a shame cause I really love it. If you could try to fix the issues that would be great but if not that's alright but thank you for your time.

### latest.log (Required)

https://gist.github.com/newperson-byte/3c1bba2bd7789fbff6da9a3fea02527c

**Comment by Fuzss** [comment]
#73
