### ISSUE TITLE
[Bug]: Mod worked, but doesn´t show items above

### ISSUE THREAD

**Issue by Ryusuke98** [Fuzss/easyanvils#76]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

v21.0.3

### Other Mods Involved (Required)

Yes

### Notes (Required)

Hey, i experienced an issue about the mod that the items are hold in the Anvil but it doesn´t show the items on top.
Is this a known Issue? Did i something wrong? 
I have the same Issue with "Visual Workbench" Mod (but not with the "Easy Magic" Mod).

My current Mod list is:
 - EasyAnvils-v21.0.3-1.21-Fabric.jar
 - EasyMagic-v21.0.2-1.21-Fabric.jar
 - EasyShulkerBoxes-v21.0.2-1.21-Fabric.jar
 - EasyShulkerBoxes-v21.0.2-1.21-Fabric.jar
 - ForgeConfigAPIPort-v21.0.8-1.21-Fabric.jar
 - iris-1.7.3+mc1.21.jar
 - lithium-fabric-mc1.21-0.12.7.jar
 - modmenu-11.0.1.jar
 - placeholder-api-2.4.1+1.21.jar
 - PuzzlesLib-v21.0.19-1.21-Fabric.jar
 - sodium-fabric-0.5.11+mc1.21.jar
 - VisualWorkbench-v21.0.1-1.21-Fabric.jar

On the Fabric Loader Version: fabric-loader-0.16.0-1.21
![2024-08-08_15 38 48](https://github.com/user-attachments/assets/437fb1a5-e38e-4962-9def-5391c8af9e61)
![2024-08-08_15 38 52](https://github.com/user-attachments/assets/99e702ae-8fdd-4e21-9c0f-a37319ed3e9c)
![2024-08-08_15 38 55](https://github.com/user-attachments/assets/aa8548ee-5259-45ad-b94e-00779a22fded)
![2024-08-08_15 39 01](https://github.com/user-attachments/assets/d758a0a5-b7a2-48d7-897f-33efd493c3cb)

### latest.log (Required)

https://gist.github.com/Ryusuke98/392b1b44ad06a058618f8b8721908fb2

**Comment by Fuzss** [comment]
Can you reproduce the issue without any other mods?

**Comment by Ryusuke98** [comment]
Yeah, i tried only "Easy Anvil/Visual Workbench" and again, Item hold in Anvil/Carfting Table but didnt show on top.

**Comment by Fuzss** [comment]
Make sure rendering is enabled in the client configs.

**Comment by Ryusuke98** [comment]
Its enabled

**Comment by Fuzss** [comment]
Fixed in v21.0.4.
