### ISSUE TITLE
[Bug]: Items left on anvil sometimes vanish

### ISSUE THREAD

**Issue by Krougal** [Fuzss/easyanvils#8]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

EasyAnvils-v4.0.5-1.19.2-Forge.jar

### Notes (Required)

Open the anvil.
Place an item and a book or 2 books on anvil.
Close anvil.
Notice the items aren't rendered.
Open the anvil.
Notice the items are gone.
This happens about 20-25% of the time for me.

Also this is not new to the latest version, as I saw the last couple updates come through, I would say it goes back at least as far as 4.0.2 but I was not using the mod prior to that version.

### latest.log (Optional)

https://gist.github.com/Krougal/a2a84ec91ff39b0d48820fc6835379ad

**Comment by Fuzss** [comment]
Thanks for the report! Can you reproduce the issue with just Easy Anvils installed?

**Comment by Fuzss** [comment]
Also are you playing ssp or smp?

**Comment by Krougal** [comment]
> Thanks for the report! Can you reproduce the issue with just Easy Anvils installed?

That would take some time to get setup, but I will get to it today.

> Also are you playing ssp or smp?

SSP

**Comment by Fuzss** [comment]
Are you sure the items are actually gone? Or are they maybe just not rendering visually, but still exist in the interface?
Also have you placed the anvil you're using before installing the mod? If so breaking and replacing should do the trick.

**Comment by Krougal** [comment]
I'm sure they are gone. I have broken several anvils since installing this mod (I built a trading hall early on and have gotten fully kitted out on traded books).

**Comment by Illios42** [comment]
This is also happening to us still! Granted we are using an older version atm but I did not see it being fixed anywhere. We are using the mod on an SMP with a forge modpack

**Comment by Fuzss** [comment]
I did make a number of changes in an attempt to fix this after v4.0.2, would be great if you could just try the latest one and report back.

**Comment by Illios42** [comment]
Ah, I see! We'll try updating and I'll let ya know if it keeps happening (fingers crossed though)

**Comment by Fuzss** [comment]
The fix for #23 should resolve this, too.
