### ISSUE TITLE
[Bug]: easyanvils-server.toml keeps resetting itself to default

### ISSUE THREAD

**Issue by purejosh** [Fuzss/easyanvils#9]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.5

### Notes (Required)

After editing the easyanvils-server.toml in the /world/serverconfigs folder, and restarting the server, the config resets itself to stock again. Is this .toml supposed to reset itself when the server is restarted? 

I have not tried using the defaultconfigs.

**Comment by Fuzss** [comment]
Did you edit the config while the server is running? Windows usually doesn't like that...

**Comment by purejosh** [comment]
Oh, interesting. Good to know.

**Comment by purejosh** [comment]
Shutting down and editing seems to have done the trick! Thanks for the heads up. :)
